Charlie Station
DeltaV-Station/Delta-v-rebase pull request #173
Opened 2023-10-14 01:48 UTC by Carolyn3114

## About the PR
A (currently) admin-only spawnable separate station.
Set place on "Charlie Station", a long lost station that predates Space Station 13 and 14, with four survivors waking up from cryosleep, finding their once state-of-the-art research facility has gone into disarray with damage, overgrowth, and fauna.

## Why / Balance
They *do* get a magnet and a circuit imprinter, not sure if this is too much.

## Technical details

## Media
I was too lazy to do maprender
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/136143032/1b28292e-ea6b-44fe-a264-1f9ee18cc2b3)

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2023-10-14 19:22 UTC, Colin-Tel commented
How is a user supposed to spawn in as an OldStationMedic or whatnot? are there spawners for these things, or is an admin just supposed to give them the outfits?

2023-10-14 19:32 UTC, Carolyn3114 commented
> How is a user supposed to spawn in as an OldStationMedic or whatnot? are there spawners for these things, or is an admin just supposed to give them the outfits?

uses ghost role spawner

2023-10-14 19:33 UTC, DebugOk requested changes

2023-10-14 19:33 UTC, DebugOk commented on Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
Improper seperation, this shouldn't be in base files

2023-10-14 19:35 UTC, Carolyn3114 commented on Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
oops

2023-10-14 19:46 UTC, Carolyn3114 commented on Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
fixed

2023-10-21 23:14 UTC, DebugOk approved these changes
Fuck it we ball

2023-10-21 23:15 UTC, Carolyn3114 commented
hip hurray

2023-10-21 23:37 UTC, merged