Removes Senior Roles
DeltaV-Station/Delta-v-rebase pull request #25
Opened 2023-09-17 17:23 UTC by FluffiestFloof

## About the PR

It comments out all the senior roles and set the ability to set their preference to false.

## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Removed the Senior Roles.

2023-09-17 17:28 UTC, DebugOk requested changes

2023-09-17 17:28 UTC, DebugOk commented on Resources/Prototypes/Roles/Jobs/departments.yml
They should stay defined here, in case they're added as late-join, because you didnt remove the roles themselves

2023-09-17 18:01 UTC, FluffiestFloof commented on Resources/Prototypes/Roles/Jobs/departments.yml
oh ye true sure

2023-09-17 19:38 UTC, FluffiestFloof commented
The real question is, do we want them to be potentially late join or entirely gone?

2023-09-17 19:41 UTC, Colin-Tel commented
```
Failed InvalidRoundstartJobsTest [70 ms]
  Error Message:
   Multiple failures or warnings in test:
  1)   Station Boxstation contains job prototype SeniorEngineer which cannot be present roundstart.
  Expected: not some item equal to "SeniorEngineer"
  But was:  < "ERTMedical", "CentralCommandOfficial", "ERTEngineer", "SeniorEngineer", "SeniorPhysician", "ERTJanitor", "ERTLeader", "SeniorResearcher", "ERTSecurity", "SeniorOfficer" >
```

Looks like we may have to comment out senior roles on maps. I can get started on it in a few minutes.

2023-09-17 19:42 UTC, Colin-Tel commented
> The real question is, do we want them to be potentially late join or entirely gone?

I think entirely gone is probably the route to take. We have no desire to really keep them in game. We'll just comment them out until we decide otherwise.

2023-09-17 19:44 UTC, FluffiestFloof commented
> > The real question is, do we want them to be potentially late join or entirely gone?
> 
> I think entirely gone is probably the route to take. We have no desire to really keep them in game. We'll just comment them out until we decide otherwise.

I'll deal with entirely commenting out the senior roles then.
Also it's weird that they create errors, is only late join roles a Nyano thing?

2023-09-17 19:54 UTC, ChilbroBaggins commented
Nyano does have some code that touches late join. Rane did something so riles like Prisoner/Gladiator/etc spawn here the marker is and not at the late join spot in arrivals.

Not sure if that's relevant here or not.

2023-09-17 19:57 UTC, DebugOk commented
> > The real question is, do we want them to be potentially late join or entirely gone?
> 
> I think entirely gone is probably the route to take. We have no desire to really keep them in game. We'll just comment them out until we decide otherwise.

Do not. This is because of the stations

2023-09-17 19:57 UTC, DebugOk commented
Comment them out in the station prototypes, not the jobs themselves

2023-09-17 20:01 UTC, Colin-Tel commented
> Comment them out in the station prototypes, not the jobs themselves

Right, that's what I meant haha.

2023-09-27 21:11 UTC, DebugOk commented
Recent merge added back incorrect entries into the map prototypes

2023-09-27 22:41 UTC, DebugOk approved these changes

2023-09-28 16:55 UTC, merged